language: node_js
node_js:
  - "6"
install:
  - cd ..
  - mkdir my
  - mv toys.hyoo.ru my/toys
  - git init
  - git remote add origin https://github.com/eigenmethod/mam.git
  - git pull origin master
  - npm install
script:
  - npm start my/toys
  - rm my/toys/.gitignore
  - mv my/toys/- toys.hyoo.ru
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: .
  on:
    branch: master
notifications:
  slack: mam-mol:Z7vokFhXaSrMlPXzq6L93bUj
