name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/setup-node@v1
    - uses: actions/checkout@v1
      with:
        repository: eigenmethod/mam
        ref: master
    - name: check
      run: |
        pwd
        ls
        cd mam
        yarn start hyoo/toys
